//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_hero1                       131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_hero2                       150
#define IDB_hero3                       151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_White                       157
#define IDB_BITMAP4                     158
#define IDB_BLACK                       158
#define IDB_BITMAP3                     162
#define IDB_MAP                         162
#define IDB_NPC_UP3                     162
#define IDB_BLUE                        163
#define IDB_HERO_LEFT_WALK0             164
#define IDB_HERO_LEFT_WALK1             165
#define IDB_HERO_LEFT_WALK2             166
#define IDB_HERO_LEFT_WALK3             167
#define IDB_HERO_LEFT_WALK4             168
#define IDB_HERO_LEFT_WALK5             169
#define IDB_HERO_LEFT_WALK6             170
#define IDB_HERO_LEFT_WALK7             171
#define IDB_HERO_RIGHT_WALK0            172
#define IDB_HERO_RIGHT_WALK1            173
#define IDB_HERO_RIGHT_WALK2            174
#define IDB_HERO_RIGHT_WALK3            175
#define IDB_HERO_RIGHT_WALK4            176
#define IDB_HERO_RIGHT_WALK5            177
#define IDB_HERO_RIGHT_WALK6            178
#define IDB_HERO_RIGHT_WALK7            179
#define IDB_BITMAP21                    180
#define IDB_HERO_SIDE                   180
#define IDB_SKULL_HURT2                 180
#define IDB_BITMAP5                     181
#define IDB_HERO_DOWN_WALK0             182
#define IDB_HERO_DOWN_WALK1             183
#define IDB_HERO_DOWN_WALK2             184
#define IDB_HERO_DOWN_WALK3             185
#define IDB_HERO_UP_WALK0               186
#define IDB_HERO_UP_WALK1               187
#define IDB_HERO_UP_WALK2               188
#define IDB_HERO_UP_WALK3               189
#define IDB_BATTLE_UI                   191
#define IDB_GRASS                       192
#define IDB_PNG1                        193
#define IDB_BITMAP6                     195
#define IDB_BATTLE_BACK                 195
#define IDB_NUM_0                       196
#define IDB_NUM_1                       197
#define IDB_NUM_2                       198
#define IDB_NUM_3                       199
#define IDB_NUM_4                       200
#define IDB_NUM_5                       201
#define IDB_NUM_6                       202
#define IDB_NUM_7                       203
#define IDB_NUM_8                       204
#define IDB_NUM_9                       205
#define IDB_ATTACK_BTN                  208
#define IDB_SKILL_BTN                   209
#define IDB_ITEM_BTN                    210
#define IDB_GUARD_BTN                   211
#define IDB_BITMAP7                     212
#define IDB_ESCAPE_BTN                  212
#define IDB_CURSOR                      213
#define IDB_SKULL                       214
#define IDB_HERO_ATTACK0                215
#define IDB_HERO_ATTACK1                216
#define IDB_HERO_ATTACK2                217
#define IDB_HERO_ATTACK3                218
#define IDB_SKULL_LEFT                  219
#define IDB_GRASS1                      220
#define IDB_BITMAP8                     221
#define IDB_HOUSE                       221
#define IDB_WATER0                      222
#define IDB_WATER1                      223
#define IDB_WATER2                      224
#define IDB_WATER3                      225
#define IDB_WATER4                      226
#define IDB_WATER5                      227
#define IDB_WATER6                      228
#define IDB_WATER7                      229
#define IDB_WATER8                      230
#define IDB_WATER9                      231
#define IDB_WATER10                     232
#define IDB_WATER11                     233
#define IDB_BITMAP10                    234
#define IDB_water12                     234
#define IDB_WATER12                     234
#define IDB_BRIDGE0                     235
#define IDB_BRIDGE1                     236
#define IDB_BRIDGE2                     237
#define IDB_BRIDGE3                     238
#define IDB_BRIDGE4                     239
#define IDB_BRIDGE5                     240
#define hero_guard                      242
#define IDB_SPIDER                      243
#define IDB_BITMAP9                     244
#define IDB_GOBLIN_IDLE0                244
#define IDB_GOBLIN_IDLE1                245
#define IDB_GOBLIN_IDLE2                246
#define IDB_GOBLIN_IDLE3                247
#define IDB_MUSHSROOM_IDLE0             248
#define IDB_MUSHSROOM_IDLE1             249
#define IDB_MUSHSROOM_IDLE2             250
#define IDB_MUSHSROOM_IDLE3             251
#define IDB_MUSHSROOM_HURT0             252
#define IDB_MUSHSROOM_HURT1             253
#define IDB_MUSHSROOM_HURT2             254
#define IDB_MUSHSROOM_HURT3             255
#define IDB_GOBLIN_HURT0                256
#define IDB_GOBLIN_HURT1                257
#define IDB_GOBLIN_HURT2                258
#define IDB_GOBLIN_HURT3                259
#define IDB_GRASS2                      260
#define IDB_GRASS3                      261
#define IDB_GRASS4                      262
#define IDB_GRASS5                      263
#define IDB_GRASS6                      264
#define IDB_CHEST0                      265
#define IDB_CHEST1                      266
#define IDB_CHEST2                      267
#define IDB_GRASS7                      268
#define IDB_BITMAP11                    270
#define IDB_LEVEL_UI                    271
#define IDB_BITMAP13                    272
#define IDB_GOLD_UI                     272
#define IDB_NPC_DOWN0                   273
#define IDB_NPC_DOWN1                   274
#define IDB_NPC_DOWN2                   275
#define IDB_NPC_DOWN3                   276
#define IDB_NPC_LEFT0                   277
#define IDB_NPC_LEFT1                   278
#define IDB_NPC_LEFT2                   279
#define IDB_NPC_LEFT3                   280
#define IDB_NPC_RIGHT0                  281
#define IDB_NPC_RIGHT1                  282
#define IDB_NPC_RIGHT2                  283
#define IDB_NPC_RIGHT3                  284
#define IDB_NPC_UP0                     285
#define IDB_NPC_UP1                     286
#define IDB_NPC_UP2                     287
#define IDB_BITMAP29                    288
#define IDB_SKULL_ATTACK9               288
#define IDB_SKULL_ATTACK7               288
#define IDB_MONEY_NUMBER_0              289
#define IDB_MONEY_NUMBER_1              290
#define IDB_MONEY_NUMBER_2              291
#define IDB_MONEY_NUMBER_3              292
#define IDB_MONEY_NUMBER_4              293
#define IDB_MONEY_NUMBER_5              294
#define IDB_MONEY_NUMBER_6              295
#define IDB_MONEY_NUMBER_7              296
#define IDB_MONEY_NUMBER_8              297
#define IDB_BITMAP12                    298
#define IDB_MONEY_NUMBER_9              298
#define IDB_GOBLIN_HURT_0               299
#define IDB_GOBLIN_HURT_1               300
#define IDB_GOBLIN_HURT_2               301
#define IDB_BITMAP14                    302
#define IDB_GOBLIN_HURT_3               302
#define IDB_SKULL_HURT_0                304
#define IDB_BITMAP15                    305
#define IDB_SPIDER_HURT_0               305
#define IDB_BITMAP16                    306
#define IDB_ROAD_0                      306
#define IDB_GOBLIN_ATTACK0              307
#define IDB_GOBLIN_ATTACK1              308
#define IDB_GOBLIN_ATTACK2              309
#define IDB_GOBLIN_ATTACK3              310
#define IDB_GOBLIN_ATTACK4              311
#define IDB_GOBLIN_ATTACK5              312
#define IDB_GOBLIN_ATTACK6              313
#define IDB_GOBLIN_ATTACK7              314
#define IDB_BITMAP17                    316
#define IDB_ITEM_MENU                   316
#define IDB_MUSHROOM_HURT0              317
#define IDB_MUSHROOM_HURT1              318
#define IDB_MUSHROOM_HURT2              319
#define IDB_MUSHROOM_HURT3              320
#define IDB_MUSHROOM_ATTACK0            321
#define IDB_MUSHROOM_ATTACK1            322
#define IDB_MUSHROOM_ATTACK2            323
#define IDB_MUSHROOM_ATTACK3            324
#define IDB_MUSHROOM_ATTACK4            325
#define IDB_MUSHROOM_ATTACK5            326
#define IDB_MUSHROOM_ATTACK6            327
#define IDB_BITMAP22                    328
#define IDB_MUSHROOM_ATTACK7            328
#define IDB_SKULL_ATTACK0               329
#define IDB_SKULL_ATTACK1               330
#define IDB_SKULL_ATTACK2               331
#define IDB_SKULL_ATTACK3               332
#define IDB_SKULL_ATTACK4               333
#define IDB_SKULL_ATTACK5               334
#define IDB_SKULL_ATTACK6               335
#define IDB_SKULL_HURT                  337
#define IDB_SKULL_HURT0                 337
#define IDB_SKULL_HURT1                 338
#define IDB_SKULL_HURT3                 340
#define IDB_SKULL_IDLE0                 345
#define IDB_SKULL_IDLE1                 346
#define IDB_SKULL_IDLE2                 347
#define IDB_SKULL_IDLE3                 348
#define IDB_FLYING_EYE_ATTACK0          349
#define IDB_FLYING_EYE_ATTACK1          350
#define IDB_FLYING_EYE_ATTACK2          351
#define IDB_FLYING_EYE_ATTACK3          352
#define IDB_FLYING_EYE_ATTACK4          353
#define IDB_FLYING_EYE_ATTACK5          354
#define IDB_FLYING_EYE_ATTACK6          355
#define IDB_FLYING_EYE_ATTACK7          356
#define IDB_FLYING_EYE_HURT0            357
#define IDB_FLYING_EYE_HURT1            358
#define IDB_FLYING_EYE_HURT2            359
#define IDB_FLYING_EYE_HURT3            360
#define IDB_FLYING_EYE_IDLE0            361
#define IDB_FLYING_EYE_IDLE1            362
#define IDB_FLYING_EYE_IDLE2            363
#define IDB_FLYING_EYE_IDLE3            364
#define IDB_FLYING_EYE_IDLE4            365
#define IDB_FLYING_EYE_IDLE5            366
#define IDB_FLYING_EYE_IDLE6            367
#define IDB_BITMAP40                    368
#define IDB_FLYING_EYE_IDLE7            368
#define IDB_BITMAP18                    369
#define IDB_POTION                      369
#define IDB_HEALING_SPELL0              370
#define IDB_HEALING_SPELL1              371
#define IDB_HEALING_SPELL2              372
#define IDB_HEALING_SPELL3              373
#define IDB_HEALING_SPELL4              374
#define IDB_HEALING_SPELL5              375
#define IDB_HEALING_SPELL6              376
#define IDB_HEALING_SPELL7              377
#define IDB_HEALING_SPELL8              378
#define IDB_HEALING_SPELL9              379
#define IDB_HEALING_SPELL10             380
#define IDB_BITMAP33                    381
#define IDB_HEALING_SPELL11             381
#define IDB_LIGHTNING_SPELL0            382
#define IDB_LIGHTNING_SPELL1            383
#define IDB_LIGHTNING_SPELL2            384
#define IDB_LIGHTNING_SPELL3            385
#define IDB_LIGHTNING_SPELL4            386
#define IDB_LIGHTNING_SPELL5            387
#define IDB_LIGHTNING_SPELL6            388
#define IDB_LIGHTNING_SPELL7            389
#define IDB_LIGHTNING_SPELL8            390
#define IDB_LIGHTNING_SPELL9            391
#define IDB_LIGHTNING_SPELL10           392
#define IDB_LIGHTNING_SPELL11           393
#define IDB_LIGHTNING_SPELL12           394
#define IDB_LIGHTNING_SPELL13           395
#define IDB_BITMAP37                    396
#define IDB_LIGHTNING_SPELL14           396
#define IDB_ITEM_POTION                 397
#define IDB_SKILL_HEAL                  398
#define IDB_SKILL_LIGHTNING             399
#define IDB_BITMAP19                    400
#define IDB_BACK                        400
#define IDB_FLYING_EYE_SKILL5           401
#define IDB_FLYING_EYE_SKILL6           402
#define IDB_BITMAP24                    403
#define IDB_FLYING_EYE_SKILL7           403
#define IDB_GOBLIN_SKILL0               404
#define IDB_GOBLIN_SKILL1               405
#define IDB_GOBLIN_SKILL2               406
#define IDB_BITMAP26                    407
#define IDB_GOBLIN_SKILL3               407
#define IDB_BITMAP20                    408
#define IDB_TUTORIAL                    408
#define IDB_FLYING_EYE_DEAD0            409
#define IDB_FLYING_EYE_DEAD1            410
#define IDB_FLYING_EYE_DEAD2            411
#define IDB_FLYING_EYE_DEAD3            412
#define IDB_GOBLIN_DEAD0                413
#define IDB_GOBLIN_DEAD1                414
#define IDB_GOBLIN_DEAD2                415
#define IDB_GOBLIN_DEAD3                416
#define IDB_MUSHSROOM_DEAD0             417
#define IDB_MUSHSROOM_DEAD1             418
#define IDB_MUSHSROOM_DEAD2             419
#define IDB_MUSHSROOM_DEAD3             420
#define IDB_SKULL_DEAD0                 421
#define IDB_SKULL_DEAD1                 422
#define IDB_SKULL_DEAD2                 423
#define IDB_SKULL_DEAD3                 424
#define IDB_BATTLE_FINISH               425
#define IDB_EXIT                        426
#define IDB_START                       427
#define IDB_TUTORIAL_FONT               428
#define IDB_TITLE                       430
#define IDB_ETHER                       432
#define IDB_BITMAP23                    433
#define IDB_SPEECH_BUBBLE               433
#define IDB_HEAL_MANA0                  434
#define IDB_HEAL_MANA1                  435
#define IDB_HEAL_MANA2                  436
#define IDB_HEAL_MANA3                  437
#define IDB_HEAL_MANA4                  438
#define IDB_HEAL_MANA5                  439
#define IDB_HEAL_MANA6                  440
#define IDB_HEAL_MANA7                  441
#define IDB_HEAL_MANA8                  442
#define IDB_HEAL_MANA9                  443
#define IDB_HEAL_MANA10                 444
#define IDB_HEAL_MANA11                 445
#define IDB_HEAL_MANA12                 446
#define IDB_HEAL_MANA13                 447
#define IDB_HEAL_MANA14                 448
#define IDB_HEAL_MANA15                 449
#define IDB_HEAL_MANA16                 450
#define IDB_HEAL_MANA17                 451
#define IDB_HEAL_MANA18                 452
#define IDB_HEAL_MANA19                 453
#define IDB_HEAL_MANA20                 454
#define IDB_HEAL_MANA21                 455
#define IDB_HEAL_MANA22                 456
#define IDB_HEAL_MANA23                 457
#define IDB_HEAL_MANA24                 458
#define IDB_HEAL_MANA25                 459
#define IDB_HEAL_MANA26                 460
#define IDB_HEAL_MANA27                 461
#define IDB_HEAL_MANA28                 462
#define IDB_HEAL_MANA29                 463
#define IDB_ICE_SPELL0                  464
#define IDB_ICE_SPELL1                  465
#define IDB_ICE_SPELL2                  466
#define IDB_ICE_SPELL3                  467
#define IDB_ICE_SPELL4                  468
#define IDB_ICE_SPELL5                  469
#define IDB_ICE_SPELL6                  470
#define IDB_ICE_SPELL7                  471
#define IDB_ICE_SPELL8                  472
#define IDB_ICE_SPELL9                  473
#define IDB_THUNDER_SPELL0              474
#define IDB_THUNDER_SPELL1              475
#define IDB_THUNDER_SPELL2              476
#define IDB_THUNDER_SPELL3              477
#define IDB_THUNDER_SPELL4              478
#define IDB_THUNDER_SPELL5              479
#define IDB_BEHEMOTH                    481
#define IDB_BEHEMOTH_ATTACK1            482
#define IDB_BEHEMOTH_ATTACK2            483
#define IDB_BEHEMOTH_ATTACK3            484
#define IDB_BEHEMOTH_ATTACK4            485
#define IDB_BEHEMOTH_ATTACK5            486
#define IDB_BEHEMOTH_ATTACK6            487
#define IDB_BEHEMOTH_ATTACK7            488
#define IDB_BEHEMOTH_ATTACK8            489
#define IDB_BEHEMOTH_ATTACK9            490
#define IDB_BEHEMOTH_ATTACK10           491
#define IDB_BEHEMOTH_ATTACK11           492
#define IDB_BEHEMOTH_ATTACK_ELECTIRC1   493
#define IDB_BEHEMOTH_ATTACK_ELECTIRC2   494
#define IDB_BEHEMOTH_ATTACK_ELECTIRC3   495
#define IDB_BEHEMOTH_ATTACK_ELECTIRC4   496
#define IDB_BEHEMOTH_ATTACK_ELECTIRC5   497
#define IDB_BEHEMOTH_ATTACK_ELECTIRC6   498
#define IDB_BEHEMOTH_ATTACK_ELECTIRC7   499
#define IDB_BEHEMOTH_ATTACK_ELECTIRC8   500
#define IDB_BEHEMOTH_ATTACK_ELECTIRC9   501
#define IDB_BEHEMOTH_ATTACK_ELECTIRC10  502
#define IDB_BEHEMOTH_ATTACK_ELECTIRC11  503
#define IDB_BEHEMOTH_ATTACK_ICE1        504
#define IDB_BEHEMOTH_ATTACK_ICE2        505
#define IDB_BEHEMOTH_ATTACK_ICE3        506
#define IDB_BEHEMOTH_ATTACK_ICE4        507
#define IDB_BEHEMOTH_ATTACK_ICE5        508
#define IDB_BEHEMOTH_ATTACK_ICE6        509
#define IDB_BEHEMOTH_ATTACK_ICE7        510
#define IDB_BEHEMOTH_ATTACK_ICE8        511
#define IDB_BEHEMOTH_ATTACK_ICE9        512
#define IDB_BEHEMOTH_ATTACK_ICE10       513
#define IDB_BITMAP63                    514
#define IDB_BEHEMOTH_ATTACK_ICE11       514
#define IDB_BITMAP25                    515
#define IDB_ABOUT                       515
#define IDB_BITMAP27                    516
#define IDB_STORY                       516
#define IDB_BITMAP28                    517
#define IDB_ESCAPEFAILED                517
#define IDB_BOSS_DOOR                   518
#define IDB_PNG2                        519
#define IDB_BITMAP30                    520
#define IDB_BATTLE_BOSS_BACKGROUND      521
#define IDB_VICTORY                     523
#define IDB_BITMAP31                    524
#define IDB_ABOUT_BTN                   525
#define IDB_THUNDER                     526
#define IDB_ACTRESS                     527
#define IDB_BITMAP34                    528
#define IDB_ACTOR                       528
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define IDB_HERO_GUARD                  32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        529
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
